site_name: Maxar Geospatial Platform


nav:
    - Home: 'index.md'
    - Quick start:
        - Admin: 'quickstarts/quickstart-admin.md'
        - Streaming: 'quickstarts/quickstart-streaming.md'
        - Discovery: 'quickstarts/quickstart-discovery.md'
        - Ordering: 'quickstarts/quickstart-ordering.md'
        - Monitoring: 'quickstarts/quickstart-monitoring.md'
    - Admin:
        - Accounts: 'account-service/account.md'
        - Users: 'account-service/users.md'
        - Usage: 'account-service/usage.md'
        - API Keys: 'token-service/tokens.md'
    - Streaming:
        - 'streaming/Streaming.md'
        - 'basemap-service/Basemap.md'
    - Analytics: 'analytics-service/Analytics-service.md'
    - Discovery: 'discovery-service/Discovery.md'
    - Monitoring: 'monitor-service/Monitor.md'
    - Ordering: 'ordering-service/Ordering.md'
    - Tasking: 'tasking-service/Tasking.md'
    - CLI Commands:
        - 'CLI Commands/cli_commands.md'
        - 'CLI Commands/account_service_cli.md'
        - 'CLI Commands/analytics_service_cli.md'
        - 'CLI Commands/basemaps_cli.md'
        - 'CLI Commands/discovery_service_cli.md'
        - 'CLI Commands/monitor_service_cli.md'
        - 'CLI Commands/order_service_cli.md'
        - 'CLI Commands/streaming_cli.md'
        - 'CLI Commands/tasking_service_cli.md'
        - 'CLI Commands/token_service_cli.md'
        - 'CLI Commands/usage_service_cli.md'
    - 'Release Notes': 'release_notes.md'

docs_dir: 'docs'
site_dir: 'site'
theme:
  name: material
  logo: maxar_gold_logo_rgb_250.png
  favicon: favicon.ico
  custom_dir: 'docs/stylesheets'
extra_css: 
    - stylesheets/extra.css

